# Generated by Django 3.2.5 on 2021-07-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_audit_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_media',
            name='object_media',
            field=models.TextField(default=''),
        ),
    ]
